version: "3"
services:
  neo4jdb:
    image: neo4j
    container_name: neo4j-container
    volumes:
      - $HOME/data/:/data
    ports:
      - 7474:7474
      - 7687:7687

  neo4j-spring-service:
    build: .
    ports:
      - 8085:8081
    depends_on:
      - neo4jdb
    links:
      - neo4jdb
    expose:
      - 8085
